baseURL = 'https://666lab.github.io/'
languageCode = 'en-us'
title = '666lab'
theme = 'digitalgarden'


[Params]
  description = "666lab 팀 블로그"
  images = ['/images/666lab.png']
  enableSearch = true

#[Params.youtubeplayer]
  #title = "Youtube"
  # description = "Play youtube videos"

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]] 
  name = 'Content'
  params.header = true
  weight = 2
[[menu.main]]
  name = '매뉴얼'
  url = '/manuals'
  weight = 3
[[menu.main]]
  name = '포스팅'
  url = '/posting'
  weight = 4
[[menu.main]]
  name = '666daeva 포스팅'
  url = '/666daeva'
  weight = 4
[[menu.main]]
  name = '팀 프로젝트'
  url = '/project'
  weight = 5
[[menu.main]]
  name = 'Links'
  params.header = true
  weight = 6
[[menu.main]]
  name = 'Proxmox'
  url = 'https://pve.666lab.org'
  weight = 7
[[menu.main]]
  name = 'Projects'
  params.header = true
  weight = 8
[[menu.main]]
  name = 'Pluto'
  url = 'https://pluto.666lab.org'
  weight = 9

[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/666lab'
  weight = 1
# [[menu.social]]
#   name = 'Twitter'
#   url = 'https://twitter.com'
#   weight = 2
# [[menu.social]]
#   name = 'LinkedIn'
#   url = 'https://linkedin.com'
#   weight = 3
# [[menu.social]]
#   name = 'Instagram'
#   url = 'https://instagram.com'
#   weight = 4
# [[menu.social]]
#   name = 'Dribbble'
#   url = 'https://dribbble.com'
#   weight = 5
# [[menu.social]]
#   name = 'Codepen'
#   url = 'https://codepen.io'
#   weight = 6
# [[menu.social]]
#   name = 'Twitch'
#   url = 'https://twitch.com'
#   weight = 7
# [[menu.social]]
#   name = 'Email'
#   # url = 'mailto:user@example.org'
#   weight = 8
[[menu.social]]
  name = 'RSS'
  url = '/blog/index.xml'
  weight = 9


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true